name: gp_prefit
# Single dataset or a list via "datasets"
#dataset: caltech101
#datasets: [oxford_pets, oxford_flowers, fgvc_aircraft, sun397, ucf101, food101, stanford_cars, eurosat, dtd]
datasets: [stanford_cars]

# Seeds and shots to sweep
seeds: [1, 2, 3]
shots: [1, 4, 8, 16]

# Optional dataset root override (falls back to defaults in utils.config)
root: /mnt/features/VDATA/

# Base trainer/dataset configs
trainer_config: configs/trainers/gp.yaml

# Where to store results for this sweep
output_root: output/search

# Grid of hyperparameters (keys follow existing config override notation)
# This config enables GP regression prefit on per-template targets
grid:
  TRAINER.ADAPTER.GP_JOINT_TRAINING: [true]

# Output directory template; placeholders available:
# {sweep}, {dataset}, {shots}, {seed}, {sig}
# {sig} is a compact signature of all grid parameters.
template: "{sweep}/{dataset}/gp_prefit_{shots}shots_{sig}/seed{seed}"


