name: gp_small
# Single dataset or a list via "datasets"
#dataset: caltech101
datasets: [caltech101, oxford_pets, oxford_flowers, fgvc_aircraft, sun397, ucf101, food101, stanford_cars, eurosat, dtd]

# Seeds and shots to sweep
seeds: [1, 2, 3]
shots: [1, 4, 8, 16]

# Optional dataset root override (falls back to defaults in utils.config)
root: /mnt/features/VDATA/

# Base trainer/dataset configs
trainer_config: configs/trainers/gp.yaml

# Where to store results for this sweep
output_root: output/search

# Grid of hyperparameters (keys follow existing config override notation)
# You can set singletons here as lists of one value.
# Examples shown for GP; remove parameters you don’t need.
grid:
  TRAINER.ADAPTER.GP_BETA: [0.0001, 0.001, 0.01]

# Output directory template; placeholders available:
# {sweep}, {dataset}, {shots}, {seed}, {sig}
# {sig} is a compact signature of all grid parameters.
template: "{sweep}/{dataset}/gp_{shots}shots_{sig}/seed{seed}"

