name: baseline_l2
dataset: caltech101

seeds: [1, 2, 3]
shots: [1, 4, 8, 16]

root: /mnt/features/VDATA/
output_root: output

# No grid by default; could add e.g., TRAINER.ADAPTER.L2_LAMBDA if desired
grid: {}

template: "{experiment}/{dataset}/baseline_{shots}shots_{sig}/seed{seed}"

# Embedded trainer configuration (from previous baseline.yaml)
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.01
  MAX_EPOCH: 300
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
  WEIGHT_DECAY: 0.0

TRAIN:
  PRINT_FREQ: 5

TRAINER:
  ADAPTER:
    INIT: ZS
    CONSTRAINT: none
    PREC: fp16
    NUM_TEMPLATES: 7
    L2_LAMBDA: 0.1
    USE_GP: False

