name: CoCoOp
BASE_CONFIG: configs/trainers/default.yaml

#datasets: [caltech101, oxford_pets, oxford_flowers, fgvc_aircraft, sun397, ucf101, food101, stanford_cars, eurosat, dtd]
datasets: caltech101

# Seeds and shots
seeds: [1, 2, 3]
shots: [1, 4, 8, 16]

# Optional dataset root override (falls back to defaults in utils.config)
root: /mnt/features/VDATA/

# Where to store results for this experiment
output_root: output

# Grid of hyperparameters (keys follow existing config override notation)
grid:
  OPTIM.NAME: [adamw]
  OPTIM.LR: [0.01]

# Output directory template
template: "{experiment}/{dataset}/cocoop_{shots}shots_{sig}/seed{seed}"

TRAINER:
  DATALOADER:
    TRAIN_X:
      BATCH_SIZE: 32
    TEST:
      BATCH_SIZE: 32
  ADAPTER:
    USE_GP: False
    TRAIN_TEMPLATE_WEIGHTS: False
    FREEZE_VISUAL_PROJ: True
    PROMPT_MODE: cocoop
    N_CTX: 16
    # Optional seed phrase, uncomment to try
    # CTX_INIT: "a photo of a"



