name: test
BASE_CONFIG: configs/trainers/default.yaml

# Dataset root
root: /mnt/features/VDATA/

# Datasets
#datasets: [caltech101, oxford_pets, oxford_flowers, fgvc_aircraft, sun397, ucf101, food101, stanford_cars, eurosat, dtd]
datasets: caltech101

# Seeds and shots
seeds: [1, 2, 3]
shots: [1, 4, 8, 16]

# Output directory template
template: "{experiment}/{dataset}/cocoop_{shots}shots_{sig}/seed{seed}"

# Hyperparameters grid
grid:
  {}

TRAINER_NAME: AdapterCoCoOp

TRAINER:
  DATALOADER:
    TRAIN_X:
      BATCH_SIZE: 32
    TEST:
      BATCH_SIZE: 32
  ADAPTER:
    USE_GP: False
    TRAIN_TEMPLATE_WEIGHTS: False
    FREEZE_VISUAL_PROJ: True
    PROMPT_MODE: cocoop
    N_CTX: 16
    # Optional seed phrase, uncomment to try
    # CTX_INIT: "a photo of a"



