DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.1
  MAX_EPOCH: 300
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
  WEIGHT_DECAY: 0.0

TRAIN:
  PRINT_FREQ: 5

TRAINER:
  ADAPTER:
    INIT: ZS  # can be ZS or RANDOM
    CONSTRAINT: none  
    PREC: fp16
    NUM_TEMPLATES: 10
    # GP-specific configuration
    USE_GP: True
    GP_KERNEL_TYPE: rbf
    GP_LENGTHSCALE: 0.3
    GP_NUM_MC_SAMPLES: 10
    GP_UPDATE_FREQ: 1  # Update every batch for better learning
    GP_LR: 0.1  # Higher learning rate for GP parameters
    GP_BETA: 0.0
    USE_VISUAL_PROJECTION: True  # Re-enable visual projection as per math formulation
    GP_FREEZE_VP: True
    GP_WARMUP_EPOCHS: 20
    GP_PHASE2_LR_FACTOR: 0.1     # GP LR ← 0.1 × warm-up LR
    GP_PHASE2_BETA: 0.02         # stronger KL after warm-up
    GP_PHASE2_UNFREEZE_VP: True  # unfreeze W after warm-up
    GP_MIN_TEMP: 20        # try 20–50