name: gp_prefit
BASE_CONFIG: configs/trainers/default.yaml
# Single dataset or a list via "datasets"
datasets: [caltech101, oxford_pets, oxford_flowers, fgvc_aircraft, sun397, ucf101, food101, stanford_cars, eurosat, dtd]

# Seeds and shots
seeds: [1, 2, 3]
shots: [1, 4, 8, 16]

# Optional dataset root override
root: /mnt/features/VDATA/

# Grid: enable GP joint training for prefit schedule
grid:
  TRAINER.ADAPTER.GP_REG_PREFIT: [false, true]
  TRAINER.ADAPTER.GP_JOINT_TRAINING: [true, false]
  TRAINER.ADAPTER.GP_REG_EPOCHS: [50, 200]
  TRAINER.ADAPTER.GP_REG_LR: [0.01, 0.1]

# Output layout
template: "{experiment}/{dataset}/gp_prefit_{shots}shots_{sig}/seed{seed}"

TRAINER:
  ADAPTER:
    USE_GP: True
    GP_KERNEL_TYPE: rbf
    GP_NUM_MC_SAMPLES: 10
    GP_LR: 0.01
    GP_BETA: 0.001

