name: test
BASE_CONFIG: configs/trainers/default.yaml

# Dataset root
root: /mnt/features/VDATA/

# Datasets
# Single dataset or a list via "datasets"
datasets: [caltech101, oxford_pets, oxford_flowers, fgvc_aircraft, sun397, ucf101, food101, stanford_cars, eurosat, dtd]

# Seeds and shots
seeds: [1, 2, 3]
shots: [1, 4, 8, 16]

# Output directory template
template: "{experiment}/{dataset}/gp_{shots}shots_{sig}/seed{seed}"

# Grid: enable GP joint training for prefit schedule
grid:
  {}

TRAINER_NAME: Adapter

TRAINER:
  ADAPTER:
    USE_GP: True
    GP_KERNEL_TYPE: rbf
    GP_NUM_MC_SAMPLES_TRAIN: 10
    GP_NUM_MC_SAMPLES_TEST: 10
    GP_LR: 0.01
    GP_BETA: 0.001

