name: gp_prefit
BASE_CONFIG: configs/trainers/default.yaml
# Single dataset or a list via "datasets"
# datasets: [caltech101, oxford_pets, oxford_flowers, fgvc_aircraft, sun397, ucf101, food101, stanford_cars, eurosat, dtd]
datasets: [caltech101, ucf101, eurosat]

# Seeds and shots
seeds: [1, 2, 3, 4, 5]
shots: [1, 2, 4, 8, 16, 32]


# Optional dataset root override
root: /mnt/features/VDATA/

# Grid: enable GP joint training for prefit schedule
grid:
  TRAINER.ADAPTER.GP_INIT_METHOD: [val_weighted, minmax]
  TRAINER.ADAPTER.GP_USE_ELBO: [true, false]

# Output layout
template: "{experiment}/{dataset}/gp_{shots}shots_{sig}/seed{seed}"

TRAINER:
  ADAPTER:
    USE_GP: True
    GP_KERNEL_TYPE: rbf
    GP_NUM_MC_SAMPLES: 30
    GP_LR: 0.001
    GP_BETA: 0.001

