DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 128
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.1
  MAX_EPOCH: 300
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
  WEIGHT_DECAY: 0.0

TRAIN:
  PRINT_FREQ: 5

TRAINER:
  ADAPTER:
    INIT: ZS  # can be ZS or RANDOM
    CONSTRAINT: none  
    PREC: fp16
    NUM_TEMPLATES: 10
    # GP-specific configuration with improved hyperparameters
    USE_GP: True
    GP_KERNEL_TYPE: rbf  # RBF generally more stable than linear
    GP_NUM_MC_SAMPLES: 10  # Fewer samples to reduce variance
    GP_USE_DIAGONAL_COV: True  # Diagonal covariance for efficiency
    GP_UPDATE_FREQ: 1  # Update every 5 batches to reduce computation
    GP_LR: 0.01  # More conservative GP learning rate
    GP_BETA: 0.1  # Much smaller KL weight to avoid overwhelming loss
    USE_VISUAL_PROJECTION: True  # Keep visual projection as per math formulation 