name: gp_small
BASE_CONFIG: configs/trainers/default.yaml
# Single dataset or a list via "datasets"
dataset: caltech101
#datasets: [caltech101, oxford_pets, oxford_flowers, fgvc_aircraft, sun397, ucf101, food101, stanford_cars, eurosat, dtd]

# Seeds and shots
seeds: [1, 2, 3]
shots: [1, 4, 8, 16]

# Optional dataset root override (falls back to defaults in utils.config)
root: /mnt/features/VDATA/

# Where to store results for this experiment
output_root: output

# Grid of hyperparameters (keys follow existing config override notation)
# You can set singletons here as lists of one value.
grid:
  TRAINER.ADAPTER.GP_REG_EPOCHS: [50, 300]
  TRAINER.ADAPTER.GP_REG_LR: [0.01, 0.1]
  TRAINER.ADAPTER.GP_JOINT_TRAINING: [true]

# Output directory template; placeholders available:
# {experiment}, {sweep} (alias), {dataset}, {shots}, {seed}, {sig}
# {sig} is a compact signature of all grid parameters.
template: "{experiment}/{dataset}/gp_{shots}shots_{sig}/seed{seed}"

TRAINER:
  ADAPTER:
    # GP-specific overrides beyond default baseline
    USE_GP: True
    GP_KERNEL_TYPE: rbf
    GP_NUM_MC_SAMPLES: 10
    GP_LR: 0.01
    GP_BETA: 0.001

