name: TipA
BASE_CONFIG: configs/trainers/default.yaml

datasets: [caltech101, oxford_pets, oxford_flowers, fgvc_aircraft, sun397, ucf101, food101, stanford_cars, eurosat, dtd]
# datasets: [caltech101, ucf101, eurosat]

# Seeds and shots
seeds: [1, 2, 3, 4, 5]
shots: [1, 2, 4, 8, 16, 32]

# Optional dataset root override (falls back to defaults in utils.config)
root: /mnt/features/VDATA/

# Where to store results for this experiment
output_root: output

# Output directory template
template: "{experiment}/{dataset}/tipa_{shots}shots_{sig}/seed{seed}"

grid:
  OPTIM.LR: [0.01]

TRAINER:
  DATALOADER:
    TRAIN_X:
      BATCH_SIZE: 32
    TEST:
      BATCH_SIZE: 32
  ADAPTER:
    BENCHMARK_METHOD: tipa
    USE_GP: False
    TRAIN_TEMPLATE_WEIGHTS: False
    FREEZE_VISUAL_PROJ: False


